### ISSUE TITLE
Modify Keithley2400 _initialize to prevent resetting

### ISSUE THREAD

**Issue by pbnjeff89** [masonlab/labdrivers#11]
This can be problematic with sweeps that do not necessarily start from source voltage V = 0. I think `write("*RST")` should be a separate, public function which could be accessed for whatever reason.

**Comment by hinnefe2** [comment]
Following up on your email here, just to make the comments easier to find:

The design decisions in the `keithley2400` driver that I'd change mostly have to do with managing the internal state of the multimeter. I remember the Keithley being kind of complicated to work with because it had lots of parameters that interact with each other (e.g. whether you're sourcing current or voltage affects how you set the compliance limits). When I made the driver I didn't do a great job of making the functions work independent of the state of the multimeter - if you call things in the order I did stuff generally works, but because the functions aren't necessarily idempotent calling things in a different order could fail.

Some of this is unavoidable because the multimeter itself maintains state, but if I redid things from scratch I'd try to do a better job of making the methods idempotent.

**Comment by pbnjeff89** [comment]
Sounds good, I'll keep that in mind. I did notice that there was a lot to consider with the SCPI commands so hopefully it won't get complicated. I have a branch in my own fork dedicated solely to testing out the Keithley stuff so that in case it is screwed up it shouldn't affect the master
